package exception

const EX_KEYSTONE_AUTH_ERROR="exception.auth.keystone.autherror"
